# Generated by Django 3.2.6 on 2021-10-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studycom', '0002_activities_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='reviewedDate',
            field=models.DateField(auto_now=True),
        ),
    ]
